language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - yarn lint
  - yarn test-ci
after_script:
  - yarn add codecov
  - node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - node_modules/.bin/codecov
